### ISSUE TITLE
Tidy up the documentation

### ISSUE THREAD

**Issue by dafitius** [glacier-modding/io_scene_glacier#6]
### Todo

- [x] Add comments where deemed necessary
- [x] Add [type hinting](https://docs.python.org/3/library/typing.html)
- [x] Put the code through [Pylint](https://pypi.org/project/pylint/)
